/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WebElements.Hyperlink.and.Image.Solution;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
